[package]
name = "pedro"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-sdk = "0.3.6"
env_logger = "0.11.3"
log = "0.4.21"
rand = "0.8.5"
tokio = { version = "1.37.0", features = ["macros"] }
